//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportService.ErrorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetActionResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetActionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private bool IsITField;
        
        private bool IgnoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsIT {
            get {
                return this.IsITField;
            }
            set {
                if ((this.IsITField.Equals(value) != true)) {
                    this.IsITField = value;
                    this.RaisePropertyChanged("IsIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Ignore {
            get {
                return this.IgnoreField;
            }
            set {
                if ((this.IgnoreField.Equals(value) != true)) {
                    this.IgnoreField = value;
                    this.RaisePropertyChanged("Ignore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Registry {
            get {
                return this.RegistryField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistryField, value) != true)) {
                    this.RegistryField = value;
                    this.RaisePropertyChanged("Registry");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorService.ErrorSearchSoap")]
    public interface ErrorSearchSoap {
        
        // CODEGEN: Generating message contract since element name ErrorCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActions", ReplyAction="*")]
        ExportService.ErrorService.GetActionsResponse GetActions(ExportService.ErrorService.GetActionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActions", ReplyAction="*")]
        System.Threading.Tasks.Task<ExportService.ErrorService.GetActionsResponse> GetActionsAsync(ExportService.ErrorService.GetActionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActions", Namespace="http://tempuri.org/", Order=0)]
        public ExportService.ErrorService.GetActionsRequestBody Body;
        
        public GetActionsRequest() {
        }
        
        public GetActionsRequest(ExportService.ErrorService.GetActionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ErrorCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Source;
        
        public GetActionsRequestBody() {
        }
        
        public GetActionsRequestBody(string ErrorCode, string Source) {
            this.ErrorCode = ErrorCode;
            this.Source = Source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportService.ErrorService.GetActionsResponseBody Body;
        
        public GetActionsResponse() {
        }
        
        public GetActionsResponse(ExportService.ErrorService.GetActionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExportService.ErrorService.GetActionResponse GetActionsResult;
        
        public GetActionsResponseBody() {
        }
        
        public GetActionsResponseBody(ExportService.ErrorService.GetActionResponse GetActionsResult) {
            this.GetActionsResult = GetActionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ErrorSearchSoapChannel : ExportService.ErrorService.ErrorSearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorSearchSoapClient : System.ServiceModel.ClientBase<ExportService.ErrorService.ErrorSearchSoap>, ExportService.ErrorService.ErrorSearchSoap {
        
        public ErrorSearchSoapClient() {
        }
        
        public ErrorSearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorSearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorSearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorSearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportService.ErrorService.GetActionsResponse ExportService.ErrorService.ErrorSearchSoap.GetActions(ExportService.ErrorService.GetActionsRequest request) {
            return base.Channel.GetActions(request);
        }
        
        public ExportService.ErrorService.GetActionResponse GetActions(string ErrorCode, string Source) {
            ExportService.ErrorService.GetActionsRequest inValue = new ExportService.ErrorService.GetActionsRequest();
            inValue.Body = new ExportService.ErrorService.GetActionsRequestBody();
            inValue.Body.ErrorCode = ErrorCode;
            inValue.Body.Source = Source;
            ExportService.ErrorService.GetActionsResponse retVal = ((ExportService.ErrorService.ErrorSearchSoap)(this)).GetActions(inValue);
            return retVal.Body.GetActionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ExportService.ErrorService.GetActionsResponse> ExportService.ErrorService.ErrorSearchSoap.GetActionsAsync(ExportService.ErrorService.GetActionsRequest request) {
            return base.Channel.GetActionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ExportService.ErrorService.GetActionsResponse> GetActionsAsync(string ErrorCode, string Source) {
            ExportService.ErrorService.GetActionsRequest inValue = new ExportService.ErrorService.GetActionsRequest();
            inValue.Body = new ExportService.ErrorService.GetActionsRequestBody();
            inValue.Body.ErrorCode = ErrorCode;
            inValue.Body.Source = Source;
            return ((ExportService.ErrorService.ErrorSearchSoap)(this)).GetActionsAsync(inValue);
        }
    }
}
