//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwSalesFlow.FNB_FUN4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FNB_FUN4.IExportPassthroughWS")]
    public interface IExportPassthroughWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/Marco", ReplyAction="http://tempuri.org/IExportPassthroughWS/MarcoResponse")]
        string Marco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/Marco", ReplyAction="http://tempuri.org/IExportPassthroughWS/MarcoResponse")]
        System.Threading.Tasks.Task<string> MarcoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/ExportSale", ReplyAction="http://tempuri.org/IExportPassthroughWS/ExportSaleResponse")]
        string ExportSale(string xmlToExport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/ExportSale", ReplyAction="http://tempuri.org/IExportPassthroughWS/ExportSaleResponse")]
        System.Threading.Tasks.Task<string> ExportSaleAsync(string xmlToExport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/EnquirePolicy", ReplyAction="http://tempuri.org/IExportPassthroughWS/EnquirePolicyResponse")]
        string EnquirePolicy(string xmlToEnquire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/EnquirePolicy", ReplyAction="http://tempuri.org/IExportPassthroughWS/EnquirePolicyResponse")]
        System.Threading.Tasks.Task<string> EnquirePolicyAsync(string xmlToEnquire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/UpgradePolicy", ReplyAction="http://tempuri.org/IExportPassthroughWS/UpgradePolicyResponse")]
        string UpgradePolicy(string xmltoUpgrade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/UpgradePolicy", ReplyAction="http://tempuri.org/IExportPassthroughWS/UpgradePolicyResponse")]
        System.Threading.Tasks.Task<string> UpgradePolicyAsync(string xmltoUpgrade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/RequestQuote", ReplyAction="http://tempuri.org/IExportPassthroughWS/RequestQuoteResponse")]
        string RequestQuote(string quoteInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportPassthroughWS/RequestQuote", ReplyAction="http://tempuri.org/IExportPassthroughWS/RequestQuoteResponse")]
        System.Threading.Tasks.Task<string> RequestQuoteAsync(string quoteInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExportPassthroughWSChannel : wwwSalesFlow.FNB_FUN4.IExportPassthroughWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportPassthroughWSClient : System.ServiceModel.ClientBase<wwwSalesFlow.FNB_FUN4.IExportPassthroughWS>, wwwSalesFlow.FNB_FUN4.IExportPassthroughWS {
        
        public ExportPassthroughWSClient() {
        }
        
        public ExportPassthroughWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportPassthroughWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportPassthroughWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportPassthroughWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Marco() {
            return base.Channel.Marco();
        }
        
        public System.Threading.Tasks.Task<string> MarcoAsync() {
            return base.Channel.MarcoAsync();
        }
        
        public string ExportSale(string xmlToExport) {
            return base.Channel.ExportSale(xmlToExport);
        }
        
        public System.Threading.Tasks.Task<string> ExportSaleAsync(string xmlToExport) {
            return base.Channel.ExportSaleAsync(xmlToExport);
        }
        
        public string EnquirePolicy(string xmlToEnquire) {
            return base.Channel.EnquirePolicy(xmlToEnquire);
        }
        
        public System.Threading.Tasks.Task<string> EnquirePolicyAsync(string xmlToEnquire) {
            return base.Channel.EnquirePolicyAsync(xmlToEnquire);
        }
        
        public string UpgradePolicy(string xmltoUpgrade) {
            return base.Channel.UpgradePolicy(xmltoUpgrade);
        }
        
        public System.Threading.Tasks.Task<string> UpgradePolicyAsync(string xmltoUpgrade) {
            return base.Channel.UpgradePolicyAsync(xmltoUpgrade);
        }
        
        public string RequestQuote(string quoteInformation) {
            return base.Channel.RequestQuote(quoteInformation);
        }
        
        public System.Threading.Tasks.Task<string> RequestQuoteAsync(string quoteInformation) {
            return base.Channel.RequestQuoteAsync(quoteInformation);
        }
    }
}
