//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportService.FNB_EFP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FNB_EFP.IExportWebService")]
    public interface IExportWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/Marco", ReplyAction="http://tempuri.org/IExportWebService/MarcoResponse")]
        string Marco();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/Marco", ReplyAction="http://tempuri.org/IExportWebService/MarcoResponse")]
        System.Threading.Tasks.Task<string> MarcoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateScheme", ReplyAction="http://tempuri.org/IExportWebService/CreateSchemeResponse")]
        string CreateScheme(string schemeXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateScheme", ReplyAction="http://tempuri.org/IExportWebService/CreateSchemeResponse")]
        System.Threading.Tasks.Task<string> CreateSchemeAsync(string schemeXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateGroup", ReplyAction="http://tempuri.org/IExportWebService/CreateGroupResponse")]
        string CreateGroup(string groupXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateGroup", ReplyAction="http://tempuri.org/IExportWebService/CreateGroupResponse")]
        System.Threading.Tasks.Task<string> CreateGroupAsync(string groupXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateGroupPolicy", ReplyAction="http://tempuri.org/IExportWebService/CreateGroupPolicyResponse")]
        string CreateGroupPolicy(string groupPolicyXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExportWebService/CreateGroupPolicy", ReplyAction="http://tempuri.org/IExportWebService/CreateGroupPolicyResponse")]
        System.Threading.Tasks.Task<string> CreateGroupPolicyAsync(string groupPolicyXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExportWebServiceChannel : ExportService.FNB_EFP.IExportWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExportWebServiceClient : System.ServiceModel.ClientBase<ExportService.FNB_EFP.IExportWebService>, ExportService.FNB_EFP.IExportWebService {
        
        public ExportWebServiceClient() {
        }
        
        public ExportWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExportWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExportWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Marco() {
            return base.Channel.Marco();
        }
        
        public System.Threading.Tasks.Task<string> MarcoAsync() {
            return base.Channel.MarcoAsync();
        }
        
        public string CreateScheme(string schemeXml) {
            return base.Channel.CreateScheme(schemeXml);
        }
        
        public System.Threading.Tasks.Task<string> CreateSchemeAsync(string schemeXml) {
            return base.Channel.CreateSchemeAsync(schemeXml);
        }
        
        public string CreateGroup(string groupXml) {
            return base.Channel.CreateGroup(groupXml);
        }
        
        public System.Threading.Tasks.Task<string> CreateGroupAsync(string groupXml) {
            return base.Channel.CreateGroupAsync(groupXml);
        }
        
        public string CreateGroupPolicy(string groupPolicyXml) {
            return base.Channel.CreateGroupPolicy(groupPolicyXml);
        }
        
        public System.Threading.Tasks.Task<string> CreateGroupPolicyAsync(string groupPolicyXml) {
            return base.Channel.CreateGroupPolicyAsync(groupPolicyXml);
        }
    }
}
